apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pytest-pipeline
  namespace: tekton-pipelines
spec:
  description: CI/CD Pipeline for Python pytest POC
  params:
    - name: git-url
      type: string
      description: Git repository URL
      default: "https://github.com/johnnynv/tekton-poc.git"
    - name: git-revision
      type: string
      description: Git revision to checkout
      default: main
    - name: git-short-sha
      type: string
      description: Short SHA for naming
      default: "latest"
  workspaces:
    - name: shared-data
      description: Shared workspace for pipeline tasks
  tasks:
    - name: run-pytest-tests
      taskRef:
        name: pytest-task
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
      workspaces:
        - name: source
          workspace: shared-data
  finally:
    - name: show-test-reports-link
      params:
        - name: git-revision
          value: $(params.git-revision)
        - name: git-short-sha
          value: $(params.git-short-sha)
      taskSpec:
        params:
          - name: git-revision
          - name: git-short-sha
        steps:
          - name: display-links
            image: alpine:latest
            script: |
              #!/bin/sh
              echo ""
              echo "🎉 ===== PYTEST EXECUTION COMPLETED ===== 🎉"
              echo ""
              
              # Get short SHA for consistent naming
              SHORT_SHA=$(echo "$(params.git-revision)" | cut -c1-8)
              FULL_SHA="$(params.git-revision)"
              
              echo "📊 Test Reports Generated Successfully!"
              echo "🎯 Git SHA: $SHORT_SHA (from $FULL_SHA)"
              echo ""
              
              echo "🔗 ===== KEY LINKS ===== 🔗"
              echo ""
              echo "📊 Test Reports Web UI:"
              echo "   🌐 Main Dashboard: http://tekton.10.117.3.193.nip.io/artifacts/"
              echo "   🎯 This Pipeline: http://tekton.10.117.3.193.nip.io/artifacts/pytest-run-$SHORT_SHA/"
              echo "   📋 View HTML reports, coverage analysis, download artifacts"
              echo ""
              echo "📈 Tekton Dashboard:"
              echo "   🏠 Main Dashboard: http://tekton.10.117.3.193.nip.io"
              echo "   🎯 This PipelineRun: http://tekton.10.117.3.193.nip.io/#/namespaces/tekton-pipelines/pipelineruns/pytest-run-$SHORT_SHA"
              echo ""
              echo "📱 GitHub Repository:"
              echo "   🔗 https://github.com/johnnynv/tekton-poc/commit/$FULL_SHA"
              echo ""
              
              echo "📋 Available Reports:"
              echo "   📈 Full Test Report (HTML)"
              echo "   💨 Smoke Tests Report" 
              echo "   📊 Code Coverage Analysis"
              echo "   📁 Coverage XML for CI/CD integration"
              echo "   📜 Execution logs and summaries"
              echo ""
              
              echo "⏱️  Reports available immediately at the Web UI link above"
              echo "✅ Pipeline completed successfully!"
              echo "=============================================="